apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mu5qykrxe-nodejs
  janus-idp.io/tekton: mu5qykrxe-nodejs
  backstage.io/kubernetes-id: mu5qykrxe-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mu5qykrxe-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
